name: firebase_start_repository
description: "A new Flutter package project."
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  package_info_plus: ^8.1.0
  start_repository_interface:
    path: ../start_repository_interface

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
