name: example
description: "Flutter_start example app"
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: any
  flutter_start:
    path: ../flutter_start/
  flutter_introduction_shared_preferences:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction.git
      path: packages/flutter_introduction_shared_preferences
      ref: 5.0.0
    # hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    # version: ^5.0.0

dependency_overrides:
  flutter_data_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_data_interface.git
      ref: 1.0.1
  flutter_introduction_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction.git
      path: packages/flutter_introduction_interface
      ref: 5.0.0
  flutter_introduction_service:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction.git
      path: packages/flutter_introduction_service
      ref: 5.0.0
  flutter_introduction_widget:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction.git
      path: packages/flutter_introduction_widget
      ref: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
  uses-material-design: true
