name: flutter_start
description: "Flutter_start is a package that allows you to jumpstart your application with a splashScreen, introduction and a home."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_introduction:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction
      ref: 2.0.0
      path: packages/flutter_introduction
  flutter_introduction_shared_preferences:
    git:
      url: https://github.com/Iconica-Development/flutter_introduction
      ref: 2.0.0
      path: packages/flutter_introduction_shared_preferences
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
